//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SamenSterker_User.SamenSterkerServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Company", Namespace="http://schemas.datacontract.org/2004/07/SamenSterker_WcfService")]
    [System.SerializableAttribute()]
    public partial class Company : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string countryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string streetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int zipcodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string city {
            get {
                return this.cityField;
            }
            set {
                if ((object.ReferenceEquals(this.cityField, value) != true)) {
                    this.cityField = value;
                    this.RaisePropertyChanged("city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string country {
            get {
                return this.countryField;
            }
            set {
                if ((object.ReferenceEquals(this.countryField, value) != true)) {
                    this.countryField = value;
                    this.RaisePropertyChanged("country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                if ((object.ReferenceEquals(this.phoneField, value) != true)) {
                    this.phoneField = value;
                    this.RaisePropertyChanged("phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string street {
            get {
                return this.streetField;
            }
            set {
                if ((object.ReferenceEquals(this.streetField, value) != true)) {
                    this.streetField = value;
                    this.RaisePropertyChanged("street");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int zipcode {
            get {
                return this.zipcodeField;
            }
            set {
                if ((this.zipcodeField.Equals(value) != true)) {
                    this.zipcodeField = value;
                    this.RaisePropertyChanged("zipcode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contract", Namespace="http://schemas.datacontract.org/2004/07/SamenSterker_WcfService")]
    [System.SerializableAttribute()]
    public partial class Contract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int companyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int contractFormulaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime endDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int numberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime startDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int companyId {
            get {
                return this.companyIdField;
            }
            set {
                if ((this.companyIdField.Equals(value) != true)) {
                    this.companyIdField = value;
                    this.RaisePropertyChanged("companyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int contractFormulaId {
            get {
                return this.contractFormulaIdField;
            }
            set {
                if ((this.contractFormulaIdField.Equals(value) != true)) {
                    this.contractFormulaIdField = value;
                    this.RaisePropertyChanged("contractFormulaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime endDate {
            get {
                return this.endDateField;
            }
            set {
                if ((this.endDateField.Equals(value) != true)) {
                    this.endDateField = value;
                    this.RaisePropertyChanged("endDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int number {
            get {
                return this.numberField;
            }
            set {
                if ((this.numberField.Equals(value) != true)) {
                    this.numberField = value;
                    this.RaisePropertyChanged("number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime startDate {
            get {
                return this.startDateField;
            }
            set {
                if ((this.startDateField.Equals(value) != true)) {
                    this.startDateField = value;
                    this.RaisePropertyChanged("startDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContractFormula", Namespace="http://schemas.datacontract.org/2004/07/SamenSterker_WcfService")]
    [System.SerializableAttribute()]
    public partial class ContractFormula : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int maxUsageHoursPerPeriodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int noticePeriodInMonthsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int periodInMonthsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double priceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int maxUsageHoursPerPeriod {
            get {
                return this.maxUsageHoursPerPeriodField;
            }
            set {
                if ((this.maxUsageHoursPerPeriodField.Equals(value) != true)) {
                    this.maxUsageHoursPerPeriodField = value;
                    this.RaisePropertyChanged("maxUsageHoursPerPeriod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int noticePeriodInMonths {
            get {
                return this.noticePeriodInMonthsField;
            }
            set {
                if ((this.noticePeriodInMonthsField.Equals(value) != true)) {
                    this.noticePeriodInMonthsField = value;
                    this.RaisePropertyChanged("noticePeriodInMonths");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int periodInMonths {
            get {
                return this.periodInMonthsField;
            }
            set {
                if ((this.periodInMonthsField.Equals(value) != true)) {
                    this.periodInMonthsField = value;
                    this.RaisePropertyChanged("periodInMonths");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Location", Namespace="http://schemas.datacontract.org/2004/07/SamenSterker_WcfService")]
    [System.SerializableAttribute()]
    public partial class Location : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Reservation", Namespace="http://schemas.datacontract.org/2004/07/SamenSterker_WcfService")]
    [System.SerializableAttribute()]
    public partial class Reservation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int companyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime createDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime endDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int locationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string locationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int numberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime startDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int companyId {
            get {
                return this.companyIdField;
            }
            set {
                if ((this.companyIdField.Equals(value) != true)) {
                    this.companyIdField = value;
                    this.RaisePropertyChanged("companyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime createDate {
            get {
                return this.createDateField;
            }
            set {
                if ((this.createDateField.Equals(value) != true)) {
                    this.createDateField = value;
                    this.RaisePropertyChanged("createDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime endDate {
            get {
                return this.endDateField;
            }
            set {
                if ((this.endDateField.Equals(value) != true)) {
                    this.endDateField = value;
                    this.RaisePropertyChanged("endDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int locationId {
            get {
                return this.locationIdField;
            }
            set {
                if ((this.locationIdField.Equals(value) != true)) {
                    this.locationIdField = value;
                    this.RaisePropertyChanged("locationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string locationName {
            get {
                return this.locationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.locationNameField, value) != true)) {
                    this.locationNameField = value;
                    this.RaisePropertyChanged("locationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int number {
            get {
                return this.numberField;
            }
            set {
                if ((this.numberField.Equals(value) != true)) {
                    this.numberField = value;
                    this.RaisePropertyChanged("number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime startDate {
            get {
                return this.startDateField;
            }
            set {
                if ((this.startDateField.Equals(value) != true)) {
                    this.startDateField = value;
                    this.RaisePropertyChanged("startDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SamenSterkerServiceReference.ISamenSterker_Service")]
    public interface ISamenSterker_Service {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISamenSterker_Service/GetAllCompanies", ReplyAction="http://tempuri.org/ISamenSterker_Service/GetAllCompaniesResponse")]
        System.Collections.Generic.List<SamenSterker_User.SamenSterkerServiceReference.Company> GetAllCompanies();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISamenSterker_Service/GetAllCompanies", ReplyAction="http://tempuri.org/ISamenSterker_Service/GetAllCompaniesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SamenSterker_User.SamenSterkerServiceReference.Company>> GetAllCompaniesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISamenSterker_Service/GetAllContracts", ReplyAction="http://tempuri.org/ISamenSterker_Service/GetAllContractsResponse")]
        System.Collections.Generic.List<SamenSterker_User.SamenSterkerServiceReference.Contract> GetAllContracts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISamenSterker_Service/GetAllContracts", ReplyAction="http://tempuri.org/ISamenSterker_Service/GetAllContractsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SamenSterker_User.SamenSterkerServiceReference.Contract>> GetAllContractsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISamenSterker_Service/GetAllContractFormula", ReplyAction="http://tempuri.org/ISamenSterker_Service/GetAllContractFormulaResponse")]
        System.Collections.Generic.List<SamenSterker_User.SamenSterkerServiceReference.ContractFormula> GetAllContractFormula();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISamenSterker_Service/GetAllContractFormula", ReplyAction="http://tempuri.org/ISamenSterker_Service/GetAllContractFormulaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SamenSterker_User.SamenSterkerServiceReference.ContractFormula>> GetAllContractFormulaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISamenSterker_Service/GetAllLocations", ReplyAction="http://tempuri.org/ISamenSterker_Service/GetAllLocationsResponse")]
        System.Collections.Generic.List<SamenSterker_User.SamenSterkerServiceReference.Location> GetAllLocations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISamenSterker_Service/GetAllLocations", ReplyAction="http://tempuri.org/ISamenSterker_Service/GetAllLocationsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SamenSterker_User.SamenSterkerServiceReference.Location>> GetAllLocationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISamenSterker_Service/GetAllReservations", ReplyAction="http://tempuri.org/ISamenSterker_Service/GetAllReservationsResponse")]
        System.Collections.Generic.List<SamenSterker_User.SamenSterkerServiceReference.Reservation> GetAllReservations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISamenSterker_Service/GetAllReservations", ReplyAction="http://tempuri.org/ISamenSterker_Service/GetAllReservationsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SamenSterker_User.SamenSterkerServiceReference.Reservation>> GetAllReservationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISamenSterker_Service/AddReservation", ReplyAction="http://tempuri.org/ISamenSterker_Service/AddReservationResponse")]
        bool AddReservation(SamenSterker_User.SamenSterkerServiceReference.Reservation reserv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISamenSterker_Service/AddReservation", ReplyAction="http://tempuri.org/ISamenSterker_Service/AddReservationResponse")]
        System.Threading.Tasks.Task<bool> AddReservationAsync(SamenSterker_User.SamenSterkerServiceReference.Reservation reserv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISamenSterker_Service/UpdateReservation", ReplyAction="http://tempuri.org/ISamenSterker_Service/UpdateReservationResponse")]
        bool UpdateReservation(SamenSterker_User.SamenSterkerServiceReference.Reservation old, SamenSterker_User.SamenSterkerServiceReference.Reservation updated);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISamenSterker_Service/UpdateReservation", ReplyAction="http://tempuri.org/ISamenSterker_Service/UpdateReservationResponse")]
        System.Threading.Tasks.Task<bool> UpdateReservationAsync(SamenSterker_User.SamenSterkerServiceReference.Reservation old, SamenSterker_User.SamenSterkerServiceReference.Reservation updated);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISamenSterker_ServiceChannel : SamenSterker_User.SamenSterkerServiceReference.ISamenSterker_Service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SamenSterker_ServiceClient : System.ServiceModel.ClientBase<SamenSterker_User.SamenSterkerServiceReference.ISamenSterker_Service>, SamenSterker_User.SamenSterkerServiceReference.ISamenSterker_Service {
        
        public SamenSterker_ServiceClient() {
        }
        
        public SamenSterker_ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SamenSterker_ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SamenSterker_ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SamenSterker_ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<SamenSterker_User.SamenSterkerServiceReference.Company> GetAllCompanies() {
            return base.Channel.GetAllCompanies();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SamenSterker_User.SamenSterkerServiceReference.Company>> GetAllCompaniesAsync() {
            return base.Channel.GetAllCompaniesAsync();
        }
        
        public System.Collections.Generic.List<SamenSterker_User.SamenSterkerServiceReference.Contract> GetAllContracts() {
            return base.Channel.GetAllContracts();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SamenSterker_User.SamenSterkerServiceReference.Contract>> GetAllContractsAsync() {
            return base.Channel.GetAllContractsAsync();
        }
        
        public System.Collections.Generic.List<SamenSterker_User.SamenSterkerServiceReference.ContractFormula> GetAllContractFormula() {
            return base.Channel.GetAllContractFormula();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SamenSterker_User.SamenSterkerServiceReference.ContractFormula>> GetAllContractFormulaAsync() {
            return base.Channel.GetAllContractFormulaAsync();
        }
        
        public System.Collections.Generic.List<SamenSterker_User.SamenSterkerServiceReference.Location> GetAllLocations() {
            return base.Channel.GetAllLocations();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SamenSterker_User.SamenSterkerServiceReference.Location>> GetAllLocationsAsync() {
            return base.Channel.GetAllLocationsAsync();
        }
        
        public System.Collections.Generic.List<SamenSterker_User.SamenSterkerServiceReference.Reservation> GetAllReservations() {
            return base.Channel.GetAllReservations();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SamenSterker_User.SamenSterkerServiceReference.Reservation>> GetAllReservationsAsync() {
            return base.Channel.GetAllReservationsAsync();
        }
        
        public bool AddReservation(SamenSterker_User.SamenSterkerServiceReference.Reservation reserv) {
            return base.Channel.AddReservation(reserv);
        }
        
        public System.Threading.Tasks.Task<bool> AddReservationAsync(SamenSterker_User.SamenSterkerServiceReference.Reservation reserv) {
            return base.Channel.AddReservationAsync(reserv);
        }
        
        public bool UpdateReservation(SamenSterker_User.SamenSterkerServiceReference.Reservation old, SamenSterker_User.SamenSterkerServiceReference.Reservation updated) {
            return base.Channel.UpdateReservation(old, updated);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateReservationAsync(SamenSterker_User.SamenSterkerServiceReference.Reservation old, SamenSterker_User.SamenSterkerServiceReference.Reservation updated) {
            return base.Channel.UpdateReservationAsync(old, updated);
        }
    }
}
